services:
  mongo:
    image: mongo:8
    container_name: desafio-ifrodados-mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null
    restart: always

volumes:
  mongo-data:
